import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import { ThemeProvider } from "@/components/providers/theme-provide";
import { Toaster } from "@/components/ui/sonner";
import localFont from "next/font/local";
import ReactQueryProvider from "@/components/providers/query-client-provider";
import NextTopLoader from "nextjs-toploader";
import { cookies } from "next/headers";
import { Header } from "@/components/header-components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const iranYekan = localFont({
  variable: "--font-iran-yekan",
  src: [
    {
      path: "../public/fonts/IRANYekanX-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/IRANYekanX-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/IRANYekanX-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the token and user data from the cookies
  const cookieStore = await cookies();
  const token = cookieStore.get("customer_access_token")?.value;

  // Determine login status
  const userStatus = token ? "loggedIn" : "loggedOut";

  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${iranYekan.variable} font-iran-yekan antialiased`}
      >
        <Header userStatus={userStatus} />

        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader />
          <ReactQueryProvider>
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
              {children}
            </div>
          </ReactQueryProvider>

          <Toaster position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
